### ISSUE TITLE
update from 0.14.7 to 0.14.8

### ISSUE THREAD

**Issue by thealphonso** [mlazarov/syncthing-centos#2]
Hello!
when trying to upgrade from the webpage to 0.14.8 I've got the permission denied error messages:

2016-10-16 14:58:28: Automatic upgrade: open /usr/bin/syncthing054630756: permission denied
2016-10-16 15:00:13: upgrading: open /usr/bin/syncthing026564662: permission denied

**Comment by mlazarov** [comment]
Try to open this issue to the Syncthing repo:
https://github.com/syncthing/syncthing

The syncthing-centos is only about the Syncthing RPM.

Martin

**Comment by thealphonso** [comment]
I was referring to the RPM version installed from your REPO

**Comment by mlazarov** [comment]
Oh, now it makes sense!

The only reasonable way to update software installed trough RPM is to update the RPM.

If you want to be able to update the software trough web you have to follow the official installation steps.
